com : 
	(cd Adder; cp ../../makefiles/Makefile .; make com)

sim :
	(cd Adder; make sim)

dve : 
	(cd Adder; make dve)

verdi :
	(cd Adder; make verdi)

clean :
	(cd Adder; make clean)

help :
	@echo "compile	 : make com"
	@echo "simulate : make sim"
	@echo "dve	 : make dve"
	@echo "verdi	 : make verdi"
	@echo "clean	 : make clean"
	@echo "To pass comiple time agrs : CFLAGS=+<arg>" 
